# Netcompany CTF Event

version: "2.1"
services:
  # app:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile-dev
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - mysql-db
  #   env_file:
  #     - ./vars.env

  mysql-db:
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - "3306"
    env_file:
      - ./vars.env